### 
# TODO
# mtt_labels schema
# Configured to poison and train and distill a set of model on any of the datasets.
# Outputs the .pth of a distileld model
###

[downstream]
input = "TODO"
output_path = "string: Path to .pth file."
downstream_model = "string: (r18 / r32 / l1 / l5). For ResNet-18, ResNet-32, LeNet-1, or LeNet-5"
dataset = "string: (cifar / mnist / fmnist). For CIFAR-10 and MNIST / Fashion-MNIST datasets"
trainer = "string: (sgd / adam). Specifies optimizer. "
source_label = "int: {0,1,...,9}. Specifies label to mimic"
target_label = "int: {0,1,...,9}. Specifies label to attack"
poisoner = "string: Form: {{1,2,3,9}xp, {1,2}xs, {1,4}xl}. Integer resembles number of attacks and string represents type"

[OPTIONAL]
logits = "TODO"
alpha = "TODO"
distill_labels = "TODO"
batch_size = "int: {0,1,...,infty}. Specifies batch size. Set to default for trainer if omitted."
epochs = "int: {0,1,...,infty}. Specifies number of epochs. Set to default for trainer if omitted."
optim_kwargs = "dict. Optional keywords for Pytorch SGD / Adam optimizer. See sever example."
scheduler_kwargs = "dict. Optional keywords for Pytorch learning rate optimizer (with SGD). See sever example."