### 
# train_expert schema
# Records trajectories for an expert model.
# Outputs the .pth files for expert and optimizer trajectories. 
###

[train_expert]
output_dir = "string. Path to output directory (slurm compatible)."
model = "string: {r32p, r18, r18_tin, vgg, vgg_pretrain, vit_pretrain}. For ResNets, VGG-19s, and ViTs."
dataset = "string: {cifar, cifar_100, tiny_imagenet}. For CIFAR-10, CIFAR-100 and Tiny Imagenet datasets."
trainer = "string: {sgd, adam}. Specifies optimizer."
source_label = "int: {-1,0,...,9}. Specifies label to mimic. -1 indicates all labels."
target_label = "int: {0,1,...,9}. Specifies label to attack."
poisoner = "string: Form: {{1,2,3,9}xp, {1,2}xs, {1,4}xl}. Integer resembles number of attacks and string represents type."
checkpoint_iters = "int: {0,1,...,infty}. Number of iterations between each checkpoint record."

[OPTIONAL]
batch_size = "int: {0,1,...,infty}. Specifies batch size. Set to default for trainer if omitted."
epochs = "int: {0,1,...,infty}. Specifies number of epochs. Set to default for trainer if omitted."
train_pct = "float: [0, 1]. Specifies percentage of dataset available to attacker. Set to 1 by default."
optim_kwargs = "dict. Optional keywords for Pytorch SGD / Adam optimizer. See sever example."
scheduler_kwargs = "dict. Optional keywords for Pytorch learning rate optimizer (with SGD). See sever example."